"""remove_embedding_id_make_node_id_primary_key

Revision ID: 9151d2c9d3bc
Revises: 9cab043cb54e
Create Date: 2025-09-10 13:23:52.619789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9151d2c9d3bc'
down_revision = '9cab043cb54e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_embeddings_node_id', table_name='embeddings')
    op.drop_constraint('uq_embedding_node_type', 'embeddings', type_='unique')
    op.drop_column('embeddings', 'id')
    # node_id를 기본키로 설정
    op.alter_column('embeddings', 'node_id', nullable=False, primary_key=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint('uq_embedding_node_type', 'embeddings', ['node_id', 'node_type'])
    op.create_index('idx_embeddings_node_id', 'embeddings', ['node_id'], unique=False)
    # ### end Alembic commands ###
