"""fix_embedding_node_id_to_string

Revision ID: 9cab043cb54e
Revises: e09fd65d4923
Create Date: 2025-09-05 11:08:32.190436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cab043cb54e'
down_revision = 'e09fd65d4923'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embeddings', 'node_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embeddings', 'node_id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
